name = "LIBSVM"
uuid = "b1bec4e5-fd48-53fe-b0cb-9723c09d164b"
version = "0.8.1"

[deps]
LIBLINEAR = "2d691ee1-e668-5016-a719-b2531b85e0f5"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
ScikitLearnBase = "6e75b9c4-186b-50bd-896f-2d2496a4843e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
libsvm_jll = "08558c22-525a-5d2a-acf6-0ac6658ffce4"

[compat]
LIBLINEAR = "0.7"
ScikitLearnBase = "0.5"
julia = "1.6"

[extras]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
RDatasets = "ce6b1742-4840-55fa-b093-852dadbb1d8b"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["DelimitedFiles", "FileIO", "JLD2", "RDatasets", "Serialization", "SparseArrays", "Statistics", "Test"]
